### PR TITLE
build: Upgrade minimum Pandas version to 1.4

### LINKED ISSUE #730: Index(...) must be called with a collection (create_adni_sessions_dict)
**Describe the bug**
I'm receiving the following error when trying to run any of my current subjects in the adni-to-bids converter:
"TypeError: Index(...) must be called with a collection of some kind, 'session_id' was passed"

**To Reproduce**
Subjects Used: 007_S_6255, 127_S_6549
1. Following the instructions at https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/ADNI2BIDS/
2. Command given: clinica convert adni-to-bids DATASET_DIRECTORY CLINICAL_DATA_DIRECTORY BIDS_DIRECTORY --subjects_list subjects.txt
3. See error:
`Traceback (most recent call last):
  File "/Users/cb/opt/anaconda3/bin/clinica", line 8, in <module>
    sys.exit(main())
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/cmdline.py", line 89, in main
    cli()
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids_cli.py", line 74, in cli
    adni_to_bids.convert_clinical_data(
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/iotools/converters/adni_to_bids/adni_to_bids.py", line 134, in convert_clinical_data
    adni_utils.create_adni_sessions_dict(
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/clinica/iotools/converters/adni_to_bids/adni_utils.py", line 723, in create_adni_sessions_dict
    df_filtered.dropna(subset="session_id", inplace=True)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 5950, in dropna
    indices = ax.get_indexer_for(subset)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5275, in get_indexer_for
    return self.get_indexer(target, **kwargs)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3437, in get_indexer
    target = self._maybe_cast_listlike_indexer(target)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5708, in _maybe_cast_listlike_indexer
    return ensure_index(target)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 6336, in ensure_index
    return Index(index_like, copy=copy)
  File "/Users/cb/opt/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 474, in __new__
    raise cls._scalar_data_error(data)
TypeError: Index(...) must be called with a collection of some kind, 'session_id' was passed`

**Desktop:**
 - OS: Apple M1 - 12.4
 - Clinica Version - 0.7.2

**Additional context**
Looking at [adni_utils.py](https://github.com/aramis-lab/clinica/blob/dev/clinica/iotools/converters/adni_to_bids/adni_utils.py), line 723:
`df_filtered.dropna(subset="session_id", inplace=True)`
I believe subset should be passed a list (i.e. ["session_id"]) instead of a just a column name. I recreated this error with the basic example in the [pandas dropna docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html). I can make the bug fix, but I feel like I'm missing something as this line hasn't been changed in some time.

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #730

### CODE REVIEW

**Review by NicolasGensollen — APPROVED** [review]
LGTM, thanks @ghisvail ! 👍

**Comment by NicolasGensollen** [comment]
I approved a bit too fast... Looks like Python 3.10 is unhappy

**Comment by ghisvail** [comment]
> I approved a bit too fast... Looks like Python 3.10 is unhappy

Looking at it 👍

**Comment by omar-rifai** [comment]
I'm having the same issue with [PR#733](https://github.com/aramis-lab/clinica/pull/733).

**Comment by ghisvail** [comment]
It's a regression from the solver in Poetry 1.2 which the GitHub action is now using by default. I just added a commit to pin the version down to 1.1.15 until this is resolved upstream.

**Comment by omar-rifai** [comment]
We should try to avoid merging before we have the green on all the checks.

**Pull request merged**
