### PR TITLE
Add section on pet-linear to CAPS specification

### LINKED ISSUE #566: Missing `pet-linear` section in the CAPS spec
A section is missing for `pet-linear` In the [CAPS specification](https://aramislab.paris.inria.fr/clinica/docs/public/latest/CAPS/Specifications/#pet-imaging-data).

Capture d’écran 2022-01-28 à 16 36 44

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #566

### CODE REVIEW

**Comment by ghisvail** [comment]
Based on my inspection of the code. Please verify on an existing dataset just in case.

**Comment by omar-rifai** [comment]
> Based on my inspection of the code. Please verify on an existing dataset just in case.

These are the outputs of `pet-linear`on the reference files we have for the non-regression tests.

└── ref
    └── caps
        └── subjects
            ├── sub-ADNI029S1384
            │   ├── ses-M00
            │   │   ├── pet_linear
            │   │   │   ├── sub-ADNI029S1384_ses-M00_task-rest_acq-fdg_pet_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-pons_pet.nii.gz
            │   │   │   └── sub-ADNI029S1384_ses-M00_task-rest_acq-fdg_pet_space-T1w_rigid.mat
            │   │   └── t1_linear
            │   │       ├── sub-ADNI029S1384_ses-M00_T1w_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_T1w.nii.gz
            │   │       ├── sub-ADNI029S1384_ses-M00_T1w_space-MNI152NLin2009cSym_res-1x1x1_T1w.nii.gz
            │   │       └── sub-ADNI029S1384_ses-M00_T1w_space-MNI152NLin2009cSym_res-1x1x1_affine.mat
            │   └── ses-M06
            │       ├── pet_linear
            │       │   ├── sub-ADNI029S1384_ses-M06_task-rest_acq-fdg_pet_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-pons_pet.nii.gz
            │       │   └── sub-ADNI029S1384_ses-M06_task-rest_acq-fdg_pet_space-T1w_rigid.mat
            │       └── t1_linear
            │           ├── sub-ADNI029S1384_ses-M06_T1w_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_T1w.nii.gz
            │           ├── sub-ADNI029S1384_ses-M06_T1w_space-MNI152NLin2009cSym_res-1x1x1_T1w.nii.gz
            │           └── sub-ADNI029S1384_ses-M06_T1w_space-MNI152NLin2009cSym_res-1x1x1_affine.mat
            └── sub-ADNI037S4015
                └── ses-M00
                    ├── pet_linear
                    │   ├── sub-ADNI037S4015_ses-M00_task-rest_acq-fdg_pet_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_suvr-pons_pet.nii.gz
                    │   └── sub-ADNI037S4015_ses-M00_task-rest_acq-fdg_pet_space-T1w_rigid.mat
                    └── t1_linear
                        ├── sub-ADNI037S4015_ses-M00_T1w_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_T1w.nii.gz
                        ├── sub-ADNI037S4015_ses-M00_T1w_space-MNI152NLin2009cSym_res-1x1x1_T1w.nii.gz
                        └── sub-ADNI037S4015_ses-M00_T1w_space-MNI152NLin2009cSym_res-1x1x1_affine.mat

**Comment by omar-rifai** [comment]
Should we also have these two:
"""
<source_file>_space-T1w_rigid.mat
 <source_file>_space-T1w_pet.nii.gz
"""

?

**Comment by ghisvail** [comment]
> Should we also have these two:
> 
> `<source_file>_space-T1w_rigid.mat` ` <source_file>_space-T1w_pet.nii.gz`
> 
> ?

We do.

**Pull request merged**
