### PR TITLE
Make documentation compatible with markdownlint

### PR DESCRIPTION
**Pull request by alexandreroutier**
- Make *.md files compatible with markdownlint.
- Make paragraphs shorter following https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length. For the moment, 'sentences ending with `.!?`' rule was used and 'clauses' rule was partially applied.
- Update year (2020 -> 2021) 
- Fix link for T1-FreeSurfer-Longitduinal (`mkdocs.yml`, `index.md`)
- Update paper (link, year) when citing ADNI

### CODE REVIEW

**Comment by mdiazmel** [comment]
HI @alexandreroutier ,
Thanks for this PR! I merged PR #181 that modifies the documentation for ADNI2BIDS converter. Can you verify that new paragraphs are  compliant with `markdownlint`, please? (This will solve the current conflict).
To be honest, I have not fully read the tool's documentation, and I feel a little bit lost on how to use it in a fluid way. Can you provide us some examples about how to call it from the command line (if this is the "right" way...). Or it should be better to use it as a plugin in the code editor? Or maybe as a pre-commit hook? From your experience, do you think that it can be used as an automatic formatting tool (or human intervention is necessary frequently)?

**Comment by alexandreroutier** [comment]
Hi @mdiazmel,

I rebased this PR for ADNI file and pushed force.

I am using markdownlint via a plugin with VSC for consistent writing like `black` for *.py files. Currently, I do not do automatic checks but you can find GitHub Actions or Node.js CLI.

Default options of VCS plugin discards `MD013/line-length` rule which can lead to debate. Since we have many URLs for papers, I found it very difficult to follow to proposed default of 80 columns. For the moment, this rule can be deactivated before an agreement.

Btw, MD007 MD033 and MD046 were occasionally deactivated for compatibility with MkDocs/Material and HTML balises.

Alex

**Comment by mdiazmel** [comment]
Hi @alexandreroutier ,

There are a couple of conflicts, probably due to recent PR merges. Could you please, take a look? 

You mention that MD007 MD033 and MD046 were "occasionally deactivated". Can you provide a configuration file for markdownlint to precise exactly under which conditions these rules were deactivated (and follow the same rules in future documents). It seems that there are files of kind `.markdownlint.jsonc` or `.markdownlint.yaml` to do this... 

I'll merge once the conflicts are resolved!

**Review by mdiazmel — APPROVED** [review]

**Comment by mdiazmel** [comment]
Thanks @alexandreroutier ,

I will merge this PR!

To note as future improvement: automatize the markdown linter in the git workflow ;)

**Pull request merged**
