### PR TITLE
Fix warnings in `merge-tsv`

### PR DESCRIPTION
**Pull request by 14thibea**
`merge-tsv` raises a lot of warning from pandas which prevents other messages from being seen.
This PR solves these issues.

### CODE REVIEW

**Comment by ghisvail** [comment]
> raises a lot of warning

Just for additional context, these warnings result from the [deprecation](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#whatsnew-140-deprecations-frame-series-append) of `pandas.DataFrame.append` in favour of `pandas.concat` since Pandas v1.4.

**Comment by ghisvail** [comment]
@14thibea what's the issue with the index though?

**Comment by 14thibea** [comment]
It is not possible to concat a DataFrame with single index with a multi-indexed DataFrame.
And I was trying to concat `ses_df` (indexed by  (participant_id, session_id)) with the content associated with each atlas which is a row indexed by 0.

**Comment by 14thibea** [comment]
also as `merge-tsv` do not write the numbered index when using a BIDS only, I removed it when a CAPS must also be merged (this is why the test is not working, in ref data there is still this useless column "Unnamed: 0")

**Comment by omar-rifai** [comment]
Thanks @14thibea.

**Pull request merged**
