### PR TITLE
Fix NIFD to BIDS conversion for MRI-only collections

### LINKED ISSUE #402: NIFD converter fails on collections with no PET data
The quality check section of the converter relies on the availability of the PET reconstruction label (`IR | RP`) for computing quality scores. The latter is not available if the collection used as input to the converter only contains MRI data.

### PR DESCRIPTION
**Pull request by ghisvail**
Also adds more accurate type signatures and prefer `None`over `pd.NA`for BIDS labels to simplify the code.

Closes #402

### CODE REVIEW

**Comment by mdiazmel** [comment]
LGTM! 

@MatthieuJoulot, can you give us your feedback wrt to the related issue (#402)?

**Comment by MatthieuJoulot** [comment]
The converter still doesn't work for me.
Screenshot 2021-09-13 at 16 47 01
I am using the case 1_S_0001

**Comment by ghisvail** [comment]
Are you sure you have the collection manifest in the imaging data folder? i.e. if your collection is called MY_COLLECTION, you should have a `/path/to/imaging_data/MY_COLLECTION_*.csv` and a `/path/to/imaging_data/NIFD` folder.

**Comment by MatthieuJoulot** [comment]
> Are you sure you have the collection manifest in the imaging data folder? i.e. if your collection is called MY_COLLECTION, you should have a `/path/to/imaging_data/MY_COLLECTION_*.csv` and a `/path/to/imaging_data/NIFD` folder.

Yes, I just checked, and I do have the collection that is correctly located.

**Comment by ghisvail** [comment]
You need #408 merged first to test this

**Comment by mdiazmel** [comment]
> You need #408 merged first to test this on this specific subject.

@MatthieuJoulot , can you test again these modification from your side, please? (#408 was merged to `dev` and rebased here).

**Comment by ghisvail** [comment]
Should be fine now

**Comment by MatthieuJoulot** [comment]
> Should be fine now

Works for me now !

**Comment by mdiazmel** [comment]
> Works for me now !

Nice! I'll merge this one!

**Review by mdiazmel — APPROVED** [review]

**Pull request merged**
