### PR TITLE
Activation of DWI CI tests

### LINKED ISSUE #549: Reactivate DWI non-regression tests once they have been validated locally
With the [latest modifications](https://github.com/aramis-lab/clinica/pull/547) to the DWI pipelines, the non-regression tests were disabled temporarily from scheduled execution (in Jenkinsfile scheduled). 

After local validation of these pipeline, we need to reactivate those tests.

### PR DESCRIPTION
**Pull request by MatthieuJoulot**
This PR makes the necessary changes to reactivate the DWI CI tests.

Closes #549

### CODE REVIEW

**Comment by ghisvail** [comment]
Requires #579

**Review by ghisvail — APPROVED** [review]

**Comment by ghisvail** [comment]
Subject to validation on next Friday's meeting.

**Review by omar-rifai — APPROVED** [review]
Looks good. Are we OK with the current comparison function? Do we have other reserves on this PR?

**Comment by MatthieuJoulot** [comment]
> Looks good. Are we OK with the current comparison function? Do we have other reserves on this PR?

Yes, the comparison function does what we want. 
Furthermore, the `similarity_measure` and `likeliness_measure` function are not doing exactly the same thing, so replacing one with the other would require more extensive researches on the reasons for which we use them.

**Pull request merged**
