### PR TITLE
Add scores

### PR DESCRIPTION
**Pull request by 14thibea**
Add new cognitive scores and the description of session-level items according to https://adni.bitbucket.io/reference/index.html by @nburgos .

### CODE REVIEW

**Review by mdiazmel — COMMENTED** [review]
Hi @14thibea,

Thanks for this! Is this a new key word available in ADNI3?

I'll merge this PR!

**Comment by 14thibea** [comment]
Hi!
Yes some keywords are only available in ADNI3.
But actually do not merge this PR now I have to clean some fields before that.

**Comment by mdiazmel** [comment]
Ok, let me know when the PR is ready!

**Comment by 14thibea** [comment]
It's ok now!

I cleaned a bit more the excel file, and also added a bugfix on `merge-tsv` --> as a subject was removed from `ADNIMERGE.csv` in ADNI3 release, it doesn't appear in participants.tsv anymore and this raised an error.

**Comment by mdiazmel** [comment]
Alright! I'll merge. 
Thanks @14thibea!

**Pull request merged**
