### PR TITLE
Add Contribution guide

### PR DESCRIPTION
**Pull request by alexandreroutier**

### CODE REVIEW

**Comment by mdiazmel** [comment]
Hi @alexandreroutier,
I added some commits to this PR and I will remove the "draft" label.
I hope that we can merge it quickly!

**Comment by alexandreroutier** [comment]
Hi @mdiazmel,

Thank you so much for continuying this PR :)

The new sections you added are very clear, I will check after a good night that everything looks good.

Alex

**Comment by alexandreroutier** [comment]
Hi @mdiazmel ,

After a last reading, I think nothing is missing :) A last review by @nburgos could be done for possible spelling mistakes, otherwise, we can safely merge.

Do you want to Squash & Merge ? If so, we can cherry pick 869bc3c regarding licensed atlases in another PR.

Alex

**Comment by mdiazmel** [comment]
> Do you want to Squash & Merge ? If so, we can cherry pick 869bc3c regarding licensed atlases in another PR.

Yes, "Squash & Merge" should be ok for this PR. Do you want to propose another PR with the changes in 869bc3c?

**Comment by alexandreroutier** [comment]
Hi @mdiazmel,

The cherry picking is done! You can Squash & Merge this one then rebase PR #159 regarding license file. :)

Alex

**Comment by nburgos** [comment]
Hi both,

I'm done with the proofreading!

Ninon

**Pull request merged**
