### PR TITLE
Source Clinica version from importlib.metadata

### PR DESCRIPTION
**Pull request by ghisvail**
The new importlib.metadata module provides a consistent way to fetch any
package version since Python 3.8 [1], and has been backported to Python
3.7 via the importlib_metadata module. It is now recommended to use this
module instead of implementing it's own version recovery mechanism [2].

[1] https://docs.python.org/3/library/importlib.metadata.html#distribution-versions
[2] https://www.python.org/dev/peps/pep-0396/

### CODE REVIEW

**Comment by ghisvail** [comment]
Now if I change the version field in `pyproject.toml` to `0.6.2` (basically where all the project metadata live now), I get:

```console
$ clinica --version
clinica, version 0.6.2
$ python -c "import clinica; print(clinica.__version__)"
0.6.2
```

**Comment by mdiazmel** [comment]
I have a behavior that is a little disturbing for me. Let me expose the steps to reproduce it:

- Create a new fresh conda env: `conda create -f environment.yml -n clinica_env`
- Install Clinica sources as developer inside the environment: `conda activate clinica_env` then `poetry install`
- Type `clinica --version`. I get the current clinica version.
- Modify the `pyproject.toml` file, by changing the metadata (the version field).
- Reinstall Clinica sources with poetry.
- Type again `clinica --version`, The version is not updated, it shows the previous value.

The only way to have the new version is by creating a new conda environment. Is that normal? I'm missing something?

**Comment by ghisvail** [comment]
> Reinstall Clinica sources with poetry.

That's where the issue is: you need to first uninstall Clinica with `pip uninstall clinica` prior to installing Clinica again with `poetry install`.

**Comment by mdiazmel** [comment]
> That's where the issue is: you need to first uninstall Clinica with `pip uninstall clinica` prior to installing Clinica again with `poetry install`.

Ok, I see, thanks. What is really disturbing is that poetry says that it has installed the new version (even if the previous one is not uninstalled with pip). 

Let's merge this PR, seems ok to me!

**Review by mdiazmel — APPROVED** [review]

**Comment by ghisvail** [comment]
> What is really disturbing is that poetry says that it has installed the new version (even if the previous one is not uninstalled with pip).

The thing is the steps you listed do work on my machine.

So perhaps it has been fixed between poetry v1.1.6 on anaconda and v1.1.11 from homebrew and conda-forge.

**Comment by mdiazmel** [comment]
> So perhaps it has been fixed between poetry v1.1.6 on anaconda and v1.1.11 from homebrew and conda-forge.

From my side, I have poetry v1.1.6 and conda 4.10.3.

**Comment by ghisvail** [comment]
> From my side, I have poetry v1.1.6 and conda 4.10.3.

What happens if you do `conda update -c conda-forge poetry` and repeat the steps?

**Comment by mdiazmel** [comment]
> What happens if you do `conda update -c conda-forge poetry` and repeat the steps?

Same case.

**Comment by ghisvail** [comment]
I tried your steps again from a fresh env and it works fine with the default `poetry` package from Anaconda.

I am not sure what's going on with your setup, tbh.

**Comment by mdiazmel** [comment]
This PR seems ready to merge. Any thoughts @omar-rifai ?

**Comment by omar-rifai** [comment]
Thanks @ghisvail, will merge.

**Pull request merged**
