### PR TITLE
CI: Autocleanup of build environments

### LINKED ISSUE #476: Better manage Conda environments in CI
conda virtual environments associated with closed PRs are currently persistent on the CI machines which causes recurrent memory problems. A set-up that automatically deletes environment associated with merged (or closed ) PRs is needed.

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #476

### CODE REVIEW

**Comment by ghisvail** [comment]
https://ci.inria.fr/clinica-aramis/blue/organizations/jenkins/clinica/detail/PR-498/23/pipeline/57

30 minutes, not too bad.

**Comment by mdiazmel** [comment]
> 30 minutes, not too bad.

Having fast feedback is definitely one of the main goals when the designing the CI architecture, at least for this project. Currently, with a few PRs by day, our (limited) resources keep idle a lot of time and we have to find a way to optimize their usage.  Having tests running in parallel is a way to do this (for example, `test iotools` and `test converters` can run in parallel, in different VMs). Response time will be faster. This can be done, under the premise that all VMs are identical (that's the case for our project) and that we guarantee that the environments inside are the same. I agree that this architecture goes beyond of classical CI approach (where all the pipeline is executed in the same agent), but we can give us some flexibility if we respect the premises underhood and if we are able to manage the constraints that this implies (e.g. create and clean the Conda environment in all the agents).

**Comment by ghisvail** [comment]
> Response time will be faster.

Maybe, maybe not. This [run](https://ci.inria.fr/clinica-aramis/blue/organizations/jenkins/clinica/detail/PR-392/40/pipeline) yesterday with parallel testing and all agents available ran in 40 minutes.

**Comment by ghisvail** [comment]
Anyway, this PR shows that autocleanup is possible using Jenkins workspaces. If you are unhappy about it, then let's invest more time in another approach.

**Comment by ghisvail** [comment]
Following the 2-minute timeout test:

Capture d’écran 2021-11-09 à 12 21 03

**Comment by mdiazmel** [comment]
Seems ok for the tests. Is it still "work in progress" ?

**Comment by ghisvail** [comment]
Afaic, it's ready to merge.

________________________________
De : mdiazmel ***@***.***>
Envoyé : mardi 9 novembre 2021 à 18:38
À : aramis-lab/clinica
Cc : VAILLANT Ghislain; Author
Objet : Re: [aramis-lab/clinica] CI: Autocleanup of build environments (PR #498)


Seems ok for the tests. Is it still "work in progress" ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faramis-lab%2Fclinica%2Fpull%2F498%23issuecomment-964380208&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cae1ee4da767746ccb15908d9a3a7be1f%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637720763113748297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FlLExYgjonGPi%2BGqNHeRInQKTQnf4%2FauE376lw2TJAA%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAO7U37FLM4O2E3WCTYFEY3ULFMBJANCNFSM5HG5LYKA&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cae1ee4da767746ccb15908d9a3a7be1f%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637720763113758293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3imv3nrohB0mNYdKW3AKzZhMp6czeEJOJHlFEHkO6nY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cae1ee4da767746ccb15908d9a3a7be1f%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637720763113758293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DIpCMq%2BMJmVOcszqCHZ4Gwva6BzJCk5JbpxT0N3pG0o%3D&reserved=0> or Android<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cae1ee4da767746ccb15908d9a3a7be1f%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637720763113768284%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4zifJRxMmeR9q%2BS5aGdscr%2BaNVHLPmQHf668BR2FvXs%3D&reserved=0>.

**Comment by ghisvail** [comment]
Automatic cancelation of previous jobs is provided by the most recent release of the [workflow-job-plugin](https://github.com/jenkinsci/workflow-job-plugin/releases/tag/workflow-job-2.42).

**Pull request merged**
