### PR TITLE
Update changelog and version for release 0.5.3

### PR DESCRIPTION
**Pull request by omar-rifai**
Update `changelog.md` and release version in `pyproject.toml` in preparation for release v0.5.3

### CODE REVIEW

**Comment by ghisvail** [comment]
I believe we are missing a version bump in the `clinica/VERSION` file.

Not sure whether it still matters though 🤔

**Comment by mdiazmel** [comment]
> I believe we are missing a version bump in the clinica/VERSION file.

> Not sure whether it still matters though 🤔

Currently it doesn't matters because after the switch to `click`, `clinica --version` reads the version information from the `pyproject.toml` file. It should be nice if this field can be recovered from the `clinica/VERSION` file. I think that this will solve the problem that I discussed in the MM chat last week (dev installation with poetry showing the same version after switching the commit in the repository).

**Comment by alexandreroutier** [comment]
Hi all,

I don't know what the 0.5.3 version will contain but it could be worth to merge PR #505 before its release. Hopefully, this would be the last PR that will fix the CLI. :)

Btw, you should mention that  the CLI for `dwi-connectome` (issue due to `--n_track` #466) and  `t1-volume*` / `pet-volume` pipelines (issue due to `--smooth` #491) were fixed.

Best,
Alex

**Comment by ghisvail** [comment]
> clinica --version reads the version information from the pyproject.toml file

Technically, it uses the new [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions) module which is now the [recommended way](https://www.python.org/dev/peps/pep-0396/#toc-entry-2) to fetch version information from now on.

**Comment by mdiazmel** [comment]
> Technically, it uses the new importlib.metadata module which is the recommended way to fetch version information from now on.

That's the reason why I propose to retrieve the version information in the `pyproject.toml` file (the package metadata) from the `clinica/VERSION` file. I would prefer not to touch this file (`pyproject.toml`) systematically at each release. If somebody knows another way to do it, go ahead. But don't bother with this, it's only a detail, I don't want to block the PR.

**Comment by ghisvail** [comment]
> > Technically, it uses the new importlib.metadata module which is the recommended way to fetch version information from now on.
> 
> That's the reason why I propose to retrieve the version information in the `pyproject.toml` file (the package metadata) from the `clinica/VERSION` file. I would prefer not to touch this file (`pyproject.toml`) systematically at each release. If somebody knows another way to do it, go ahead. But don't bother with this, it's only a detail, I don't want to block the PR.

Moved to https://github.com/aramis-lab/clinica/pull/508

**Pull request merged**
