### PR TITLE
Apply black formatting to DWI-Connectome

### PR DESCRIPTION
**Pull request by alexandreroutier**
Also used f-string formatting as well as calls to some function in `utils/*.py`.

### CODE REVIEW

**Comment by ghisvail** [comment]
I am not convinced of the value provided by this PR close to a release. It's a large reformatting patch and it's time-consuming to review. Better to postpone this reformatting early in the next development cycle and maybe apply it to the whole code base as opposed to just `dwi-connectome`.

**Comment by ghisvail** [comment]
Closing in favor of a future run of `black` and `isort` on the whole code base.

**Comment by alexandreroutier** [comment]
Hi @ghisvail,

The pipeline is the last one that did not have `black` formatting with special attention to node connections (`# fmt: on/off` was used after manual formatting).

Best,
Alex

**Comment by mdiazmel** [comment]
Let me reopen this PR, in fact as @alexandreroutier mentions, `black` and `isort` was already applied to the whole code base (see 1c4ee411) with only a few exceptions. This pipeline is part of these exceptions.

**Pull request merged**
