### PR TITLE
Fix `merge-tsv` according to new PET format

### PR DESCRIPTION
**Pull request by 14thibea**
- Replace `acq` by `trc` 
- Fix pvc_restriction

### CODE REVIEW

**Comment by 14thibea** [comment]
Obviously, the input data of non-regression tests must be changed (it should not contain pet images with key `acq`).

**Comment by omar-rifai** [comment]
Good catch, I'll try to merge this asap.

**Comment by ghisvail** [comment]
> Obviously, the input data of non-regression tests must be changed (it should not contain pet images with key `acq`).

I just checked the CI data and all occurrences of `acq-` have already been replaced by `trc-`, both in the input dataset and the reference TSV file.

```shell
> grep 'acq' ./ref/output_file.tsv
<empty>
> grep 'trc' ./ref/output_file.tsv
<whole TSV header>
```

```shell
> find in/ -name '*acq-*'
<empty>
> find in/ -name '*trc-*'
in//bids/sub-ADNI002S2010/ses-M00/pet/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet.nii.gz
in//bids/sub-ADNI002S2010/ses-M00/pet/sub-ADNI002S2010_ses-M00_trc-18FAV45_pet.nii.gz
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-Neuromorphometrics_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-LPBA40_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-Hammers_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-AAL2_pvc-rbv_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-AICHA_pvc-rbv_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-LPBA40_pvc-rbv_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-Neuromorphometrics_pvc-rbv_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-AAL2_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-AICHA_suvr-pons_statistics.tsv
in//caps/subjects/sub-ADNI002S2010/ses-M00/pet/preprocessing/group-ADNIbl/atlas_statistics/sub-ADNI002S2010_ses-M00_trc-18FFDG_pet_space-Hammers_pvc-rbv_suvr-pons_statistics.tsv
```

The issue lies elsewhere.

**Comment by omar-rifai** [comment]
> I just checked the CI data and all occurrences of `acq-` have already been replaced by `trc-`, both in the input dataset and the reference TSV file.

The input files have indeed the `trc`key. However, the changes @14thibea proposes  will add the `trc` information in the column names that require it (so just more `trc`matches than currently).

**Comment by omar-rifai** [comment]
@ghisvail, what are those last two commits? the PR seems unchanged.

**Pull request merged**
