### PR TITLE
Remove type hints from nipype function node

### PR DESCRIPTION
**Pull request by ghisvail**
It turns out nipype's requirements for custom functions are incompatible with the typing module.

See #453

### CODE REVIEW

**Review by omar-rifai — CHANGES_REQUESTED** [review]
Some similar changes in other pipelines need to be made as well.

**Comment by alexandreroutier** [comment]
Hi everyone,

Is it possible to wait for the merge of PR #346 before touching the files mentioned by @omar-rifai? I am afraid that it will generate again some conflicts on the PR.

Alex

**Comment by ghisvail** [comment]
> Is it possible to wait for the merge of PR #346

How long?

**Comment by ghisvail** [comment]
> It may be worthwhile double checking to see if I missed some.

I have skimmed through all `clinica/utils` and took this opportunity to fix some issues reported by PyCharm along the way.

**Comment by ghisvail** [comment]
> I am afraid that it will generate again some conflicts on the PR.

I have looked at your PR, tbh there is not that much overlap so conflicts should be manageable. I'll deal with them if you want.

**Comment by omar-rifai** [comment]
> Hi everyone,
> 
> Is it possible to wait for the merge of PR #346 before touching the files mentioned by @omar-rifai? I am afraid that it will generate again some conflicts on the PR.
> 
> Alex

 PR #346 looks good to be merged. Any reserves @alexandreroutier ?

**Comment by alexandreroutier** [comment]
> > I am afraid that it will generate again some conflicts on the PR.
> 
> I have looked at your PR, tbh there is not that much overlap so conflicts should be manageable. I'll deal with them if you want.

Awesome, I was afraid about the overlap.

> > Hi everyone,
> > Is it possible to wait for the merge of PR #346 before touching the files mentioned by @omar-rifai? I am afraid that it will generate again some conflicts on the PR.
> > Alex
> 
> PR #346 looks good to be merged. Any reserves @alexandreroutier ?

No 🔥

**Comment by ghisvail** [comment]
I have successfully rebased this PR on top of the latest changes.

And congrats @alexandreroutier for #346 :tada:

**Review by omar-rifai — APPROVED** [review]

**Pull request merged**
