### PR TITLE
WIP: CI experiments

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by omar-rifai** [comment]
@ghisvail, thanks but please consult before working on tangent tasks to avoid duplicate effort (I was working this task and discussing with @mdiazmel on the best course of action)

**Comment by ghisvail** [comment]
Sure, that was just a test on my spare time.
________________________________

**Comment by omar-rifai** [comment]
@mdiazmel, does this approach seem reasonable to you ? (i.e forcing a single  agent to work on the task from start to end?)

**Comment by ghisvail** [comment]
Superseded by #498

**Pull request closed without merging**
