### PR TITLE
Use CSD interface instead of EstimateFOD

### LINKED ISSUE #687: NodeExecutionError: Node 1b-FODEstimation.
This issue happens when I ran the dwi_connectome pipeline (Fig. 1). After checking the recorded command of 1b-FODEstimation in work directory , rerunning it and getting an error message(Fig. 2), I thought I had solved this problem and then I cut off those wrong output files(gm.mif and csf.mif) in the clinicaEnv/lib/python3.8/site-packages/nipype/interfaces/mrtrix3/reconst.py (Fig 3). Then I  ran the dwi_connectome again and got another problem(Fig 4).

ͼƬ1
ͼƬ2
Figure 1

ͼƬ3
Figure 2

ͼƬ4
Figure 3

ͼƬ5
Figure 4

### PR DESCRIPTION
**Pull request by ghisvail**
See https://github.com/nipy/nipype/issues/2822

Closes #687

### CODE REVIEW

**Comment by ghisvail** [comment]
Building the docs fail because Jenkins is drunk.

**Comment by omar-rifai** [comment]
Hi @ghisvail, thanks for the PR. Can you please build on your fork instead of creating a new branch. It avoids maintaining several branches in jenkins.

**Comment by ghisvail** [comment]
> Can you please build on your fork instead of creating a new branch.

:+1: 

> It avoids maintaining several branches in jenkins.

This should avoid this too.

Capture d’écran du 2022-07-21 23-02-06

**Comment by omar-rifai** [comment]
Ok, I'll let you close this and create a new branch out of your fork then. Please also verify that the relevant pipelines run correctly.

**Comment by ghisvail** [comment]
CI for the PR ran fine. It can be merged.

I don't have access to a machine with a proper git setup at this time, hence why I used the "edit with GitHub" feature.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by omar-rifai** [comment]
Closing in favor of #710. Unfortunately the CI does not test for this pipeline, hence my request above. But I have tested separately and all good 👍🏼

**Pull request closed without merging**
