### PR TITLE
Enh bye freesurfer conv

### PR DESCRIPTION
**Pull request by MatthieuJoulot**
Remove the usage of FreeSurfer as a fallback for dcm2niix conversion in the `aibl-to-bids` converter.

To do:

- [x]  test the aibl database to see whether FreeSurfer is used and is useful to convert. 3 conversion are done using FreeSurfer. 
- [x] Download them again to be sure they were not updated and now work.
- [ ] If they still do not work-> Indicate these cases to dcm2niix so they can fix them.

### CODE REVIEW

**Comment by ghisvail** [comment]
Could you verify there is no longer any ref to freesurfer in the docs for the converters?

**Comment by MatthieuJoulot** [comment]
@ghisvail done !

**Comment by ghisvail** [comment]
> @ghisvail done !

Here: https://github.com/aramis-lab/clinica/blob/dev/docs/Third-party.md#third-party-software

**Comment by MatthieuJoulot** [comment]
@ghisvail good catch, thanks !

**Review by ghisvail — APPROVED** [review]

**Comment by MatthieuJoulot** [comment]
- [x] The four T1 cases that did not work with dcm2niix and needed FreeSurfer, work when downloaded again.

They will need to be updated on the Lustre.

**Pull request merged**
