### PR TITLE
Add instructions for clinical and imaging folder preparation

### LINKED ISSUE #238: Some questions about adni-to-bids
What is happening?
This is the first time for me and my team to use the clinica.

I have downloaded a large range datas about ADNI from the websit.

But when I looked the unzip files, I was lost in thought. There were too many datas! I thought that should I merge the datas according to matedata, or should I use `clinica convert adni-to-bids NEW1/ADNI clinical_data BIDS -m T1` and `clinica run adni-to-bids NEW2/ADNI clinical_data BIDS -m T1` and so on? 

Thought twice, I decided to use the second method to convert the datasets.  Luckly, it seemed that I had convert the datasets successfully. However, when I run `clinica run t1-volume BIDS CAPS label`, some wrong happened in the 1/4 `t1-volume-tissue-segmentation`: CAPS outputs were not found for some image(s) . I had a issue https://github.com/aramis-lab/clinica/issues/219, the answer was the MATLAB or SPM12 version error. 

I thought twice, and then decided to merge a single test called 4449 , and run `convert` successfully, and run `t1-volume `successfully! I was shocked! 

According to my experience, should I merge so many ADNI datasets? 

Hopefully to receive the replay

Thanks

### PR DESCRIPTION
**Pull request by ghisvail**
Instructions for ADNI are missing a paragraph on how to process the archives downloaded from the LONI interface to obtain the clinical and imaging directories in the layout expected by the converter.

Closes #238

### CODE REVIEW

**Comment by ghisvail** [comment]
I took this opportunity to fix the layout of a table and a numbered list.

**Review by mdiazmel — COMMENTED** [review]
Cool ! Thx @ghisvail .

Btw, in you experience with ADNI, do the platform administrators  frequently modify the interface (or the steps required) to download the dataset? If yes, it may be worth to add  something like "at the date (September 2021), the process to download the data is ..."

**Comment by ghisvail** [comment]
> Btw, in you experience with ADNI, do the platform administrators frequently modify the interface (or the steps required) to download the dataset? If yes, it may be worth to add something like "at the date (September 2021), the process to download the data is ..."

The LONI interface has not changed since I started, therefore I don't think this notice would be useful. An area for improvement though would be to replace the instructions on where to click with annotated screenshots.

**Comment by mdiazmel** [comment]
> The LONI interface has not changed since I started, therefore I don't think this notice would be useful. An area for improvement though would be to replace the instructions on where to click with annotated screenshots.

Yes, that should be really nice! Can you take this on charge in this PR?

**Comment by ghisvail** [comment]
Imo, it should be the topic for another PR and applied to all converters, not just ADNI.

________________________________
De : mdiazmel ***@***.***>
Envoyé : vendredi 24 septembre 2021 à 10:18
À : aramis-lab/clinica
Cc : VAILLANT Ghislain; Mention
Objet : Re: [aramis-lab/clinica] Add instructions for clinical and imaging folder preparation (#432)


The LONI interface has not changed since I started, therefore I don't think this notice would be useful. An area for improvement though would be to replace the instructions on where to click with annotated screenshots.

Yes, that should be really nice! Can you take this on charge in this PR?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faramis-lab%2Fclinica%2Fpull%2F432%23issuecomment-926439251&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cddff81aca46f4e0a324008d97f33e668%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637680683161319459%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=R%2F3jwv8EiCLJ7BFOEVif%2Bs5BJfSGCV%2FJ1UrEcJwAhVg%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAO7U37LGDRDM3AO3ALNNWLUDQX5RANCNFSM5ET455GQ&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cddff81aca46f4e0a324008d97f33e668%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637680683161329444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=j7o1Mtei095z8B2j48YdVKq2L1N93GJxI47Q7J9IlBI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cddff81aca46f4e0a324008d97f33e668%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637680683161329444%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NGS4zqiNKXOZCM6qb6na%2BQL%2FeGVjq5xXnE0TP9eZSzs%3D&reserved=0> or Android<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cghislain.vaillant%40icm-institute.org%7Cddff81aca46f4e0a324008d97f33e668%7C9df7cf1718fa41508b00dc5e754777d8%7C0%7C0%7C637680683161339438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rSVu9J6RzFwW9UDS2nvS5wfmP4pyNZPtKnmRAH%2Fr%2BiE%3D&reserved=0>.

**Pull request merged**
