### PR TITLE
Bugfix + improve documentation

### PR DESCRIPTION
**Pull request by 14thibea**
This PR intends to fix a small bug in an error print.
It also adds a line on how to download ADNI as many users are asking for the same thing in Clinica Google group.

### CODE REVIEW

**Comment by 14thibea** [comment]
Finally, I also added some changes in ADNI converter to convert scan information... (nothing was done so far).
So this PR is a bit heterogeneous.

**Comment by nburgos** [comment]
The documentation is clear!

**Review by mdiazmel — COMMENTED** [review]
Hi @14thibea ,
Seems ok, I'll merge this PR. 
Can you please provide me a list of subjects, to use with the argument `--subjects_list` and include them in the testing data ? 2 or 3 subjects with different modalities should be enough!

**Comment by 14thibea** [comment]
Is it for the ADNI converter?

**Comment by mdiazmel** [comment]
> Is it for the ADNI converter?

 Right!

**Pull request merged**
