### PR TITLE
New version of DWI preprocessing pipelines (Rebased version)

### PR DESCRIPTION
**Pull request by alexandreroutier**
Rebased version of PR #59.

This PR contains new versions of DWI-Preprocessing pipelines. They all rely on `eddy` tool [[Andersson et al., 2016](https://dx.doi.org/10.1016%2Fj.neuroimage.2015.10.019)] from FSL

- A very close version of `dwi-preprocessing-using-t1w` was evaluated in [[Wen et al., 2020](https://hal.inria.fr/hal-02566361v2/document)]
- `dwi-preprocessing-using-phasediff-fmap` will be evaluated a final time before merging

### CODE REVIEW

**Comment by mdiazmel** [comment]
Seems that it needs a recent version of FSL to run this pipeline, isn't @alexandreroutier ?

**Comment by alexandreroutier** [comment]
> Seems that it needs a recent version of FSL to run this pipeline, isn't @alexandreroutier ?

Yes. FSL 6.X version is needed on top of [Convert3D 1.0](http://www.itksnap.org/pmwiki/pmwiki.php?n=Downloads.C3D) for the version using T1w image for EPI correction.

**Comment by mdiazmel** [comment]
>  Yes. FSL 6.X version is needed on top of Convert3D 1.0 for the version using T1w image for EPI correction.

I updated the dependencies in the CI machines and I also installed Convert3D. Normally, the test will run once the conflicts are fixed.

**Comment by omar-rifai** [comment]
Hi @alexandreroutier, 

Thanks for your work ! This looks good with a few minor changes to be in line with the new logging and CLI convention to be included when rebasing with the current dev.

Let's merge this soon 👍 ;)

**Comment by alexandreroutier** [comment]
Continues in #346.

**Pull request closed without merging**
